services:
  db:
    image: postgres
    container_name: ems-postgres-db
    restart: always
    environment:
      POSTGRES_DB: ems_db
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgre_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  postgre_db:
    driver: local



# volumes:
#   postgre_db:
#     driver: local
#     driver_opts:
#       type: none
#       device: ${PWD}/postgre-db
#       o: bind
#       # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
